# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a4597c2bcace611901e291f8b364f0064b439d9ff6a8b78417c94e6b06de3fd39d307ad047a1be06301b703ee9f903b09ba59fea86575274c6fb679043165af
  secret_mailgun_account: postmaster@sandbox470e2d30a4f24547915523ce04bfece9.mailgun.org
  secret_mailgung_password: 4f991f96349622f9e96d11b553c523fd
  secret_googlemapsapi_key: //maps.google.com/maps/api/js?key=AIzaSyB6ZNA460OEySGAfz57evW312lrAuUjLu8

test:
  secret_key_base: 3ca2734cb79c072317c632feec3d56c4c7c1aabd72a7b0494fa28c1a96d4d4271f5e249a394c3cec36f3ad94dd7456268a670740b85bbf91aa7cdff15cd3fa71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_mailgun_account: postmaster@sandbox470e2d30a4f24547915523ce04bfece9.mailgun.org
  secret_mailgung_password: 4f991f96349622f9e96d11b553c523fd
  secret_googlemapsapi_key: //maps.google.com/maps/api/js?key=AIzaSyB6ZNA460OEySGAfz57evW312lrAuUjLu8
